#NUMPY ASSIGNMENT

In [4]:
import numpy as np

Methods for creating arrays


In [5]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [6]:
arr2 = np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
arr3 = np.ones((2,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
arr4 = np.random.randint(1,100, size=(2,3))
print(arr4)

[[43  2 33]
 [19 64 72]]


Array Properties

In [17]:
vtr = np.array([1, 2, 3, 4])
mtr = np.array([[1, 2, 3], [4, 5, 6]])

print("Vector:", vtr)
print("Matrix:\n", mtr)
print("\n")
print("Shape of vector:", vtr.shape)
print("Shape of matrix:", mtr.shape)
print("Dimensions(axes) of matrix:", mtr.ndim)
print("Data type:", mtr.dtype)
print("Total elements:", mtr.size)

Vector: [1 2 3 4]
Matrix:
 [[1 2 3]
 [4 5 6]]


Shape of vector: (4,)
Shape of matrix: (2, 3)
Dimensions(axes) of matrix: 2
Data type: int64
Total elements: 6


Indexing of Array


In [19]:
arr1 = np.array([10,20,30,40,50])

print(arr1[0])
print(arr1[2])
print(arr1[-1])

10
30
50


In [22]:
arr2 = np.array([[1,2,3],
                [4,5,6]])

print(arr2[1,2])
print(arr2[0,2])

6
3


Slicing


In [ ]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::-1])

Arithmetic operations

In [23]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[100 400 900]


Statistical Operations

In [24]:
marks = np.array([70,80,90,60,85])

print(np.sum(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.std(marks))
print(np.var(marks))
print(np.min(marks))
print(np.max(marks))

385
77.0
80.0
10.770329614269007
116.0
60
90


Example

In [25]:
marks = np.array([78,65,92,85,74])

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Above 75:", marks[marks>75])

Average: 78.8
Highest: 92
Lowest: 65
Above 75: [78 92 85]


Conclusion


In [ ]:
print("NumPy makes numerical computation faster and easier.")
print("It is the foundation of many AI and Machine Learning libraries.")